[package]
name = "kraken-feed"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
rdkafka = "0.39.0"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
tokio-tungstenite = "0.28.0"
tracing = "0.1.44"
